### ISSUE TITLE
Success does not mean a preparation was created successfully

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qp-knight-lab-processing#53] opened 2023-04-13 17:41 UTC
This is related to #51, but more definitively shown with job 15d22063-7b43-4e66-b69c-d51f7b5575b1. The processing pipeline reports success. However, the prep was not successfully created (see prep ID 14653).

**Comment by charles-cowart** [comment] 2023-04-13 22:27
The issue is that the extent of QPP's involvement w/generating preps is limited to posting the prep-information file to Qiita:
https://github.com/qiita-spots/qp-knight-lab-processing/blob/8696401a3aa4bdce6135b5a66e6186af8da603b8/qp_klp/process_metagenomics_job.py#L289-L300

It appears that https://github.com/qiita-spots/qiita/blob/b8e151e2bb7be065192edd187b31f96d6dac1101/qiita_db/handlers/prep_template.py#L120-L128 will default to returning 200 and the new prep-id as long an Error wasn't raised.

The full creation of the prep (I believe) is performed downstream of this POST call and involves creating jobs outside of the QPP.

We could introduce a poll into QPP to confirm that the full prep as it's seen in the UI was successfully created. I'd probably confirm with @antgonza whether we can do this with existing REST calls to Qiita or whether a new call would be best.

**Comment by charles-cowart** [comment] 2023-09-14 18:46
The SPP now links the files directly and reports the job-id linking the files in the touched_studies.html file. @antgonza and I agree this issue can be closed as it's now easy to trace a failed prep-file creation back to the responsible job.

**Closed by charles-cowart** 2023-09-14 18:46 UTC
